management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  redis:
    host: brewdis-enterprise.eastus2.redisenterprise.cache.azure.net
    port: 10000

stomp:
  host: dashaun-brewdis-brewdis.azuremicroservices.io
  port: 80
